# Generated by Django 3.0.3 on 2020-04-19 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='titanic_guess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passengerclass', models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third')])),
                ('sex', models.IntegerField(choices=[(0, 'Female'), (1, 'Male')])),
                ('age', models.IntegerField(default=0)),
                ('relativesonboard', models.IntegerField(default=0)),
                ('ticketprice', models.FloatField(default=0)),
            ],
        ),
    ]
