# Generated by Django 3.0.3 on 2020-04-30 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titanic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='titanic_guess',
            old_name='ticketprice',
            new_name='fare',
        ),
        migrations.RenameField(
            model_name='titanic_guess',
            old_name='passengerclass',
            new_name='pclass',
        ),
        migrations.RenameField(
            model_name='titanic_guess',
            old_name='relativesonboard',
            new_name='relatives',
        ),
    ]
